spring:
    application:
        name: estagiou

    profiles:
        # Active profile (development, produce, test. Default: development)
        active: development

    datasource:
        url: jdbc:postgresql://localhost:5432/estagiou
        # Add username datasource (Default: postgres)
        username: 
        # Add password datasource
        password: 

    mail:
        enable: false
        host: smtp.gmail.com
        port: 587
        # Add email username
        username: 
        # Add email password
        password: 
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    secret:

logs:
    show:
        enable: false
    save:
        enable: false

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs